"""Added delete cascade for itinerary and places

Revision ID: 709f4a31bf4d
Revises: dbddfff4a999
Create Date: 2024-06-13 17:04:41.885901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709f4a31bf4d'
down_revision: Union[str, None] = 'dbddfff4a999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_place', schema=None) as batch_op:
        batch_op.drop_constraint('itinerary_place_itinerary_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'itinerary', ['itinerary_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_place', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('itinerary_place_itinerary_id_fkey', 'itinerary', ['itinerary_id'], ['id'])

    # ### end Alembic commands ###
