"""empty message

Revision ID: dd93777c7275
Revises: c1f7de5211ac
Create Date: 2024-06-10 00:46:50.583456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd93777c7275'
down_revision = 'c1f7de5211ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_place', schema=None) as batch_op:
        batch_op.drop_constraint('itinerary_place_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('itinerary_place_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
